name: Setup Python & uv
description: Setup Python and uv package manager

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.11"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: uv sync
